name: CICD Testing
on: 
 workflow_dispatch:
  inputs:
   description: "Start Build"
   required: true
   type: boolean
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref && github.ref || github.run_id }}
  cancel-in-progress: true
  jobs:
   geting_details:
    runs-on: ubuntu-latest
     steps:
      - name: checkout code  
        uses: actions/checkout@v6
      - name: print details
        run: ${{ github.head_ref || github.ref_name }}
