name: CICD Testing

on:
  workflow_dispatch:
    inputs:
      start_build:
        description: "Start Build"
        required: true
        type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  getting_details:
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.start_build }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print branch or ref
        run: echo "Ref: ${{ github.head_ref || github.ref_name }}"
