name: CICD Testing

on:
  workflow_dispatch:
    inputs:
      start_build:
        description: "Start Build"
        required: true
        type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  getting_details:
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.start_build == true }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print branch or ref
        run: echo "Hello World"

      - name: Print Github Variable
        run: |
         echo "${{ github.workflow }}"
         echo "${{ github.head_ref }}"
         echo "${{ github.run_id }}"

      - name: Determine tag name
        id: tag
        uses: ./.github/actions/get-tag-name

      - name: Pack artifacts
        id: pack_artifacts
        run: |
          echo "${{ steps.tag.outputs.name }}"
